name: Code-Related Issue
description: Use this template to start code-related issues for the project.

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the Issue
      description: What’s wrong or what are you trying to achieve?
      placeholder: |
        Ex: “When I click Save, the form clears but nothing is sent to the server.”

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: What are the objectives of this issue and how will they be solved?
      placeholder: |
        - Fix the bug in feature X.  
        - Make sure all tests in the CI/CD Pipeline pass.  
        - Validate solution with others before pushing.

  - type: textarea
    id: solution
    attributes:
      label: Describe the Solution
      description: What do you want to happen?
      placeholder: |
        Ex. The submit button should no longer cause the website to crash.

  - type: textarea
    id: files
    attributes:
      label: Relevant Files
      description: What files are/were relevant to this issue?
      placeholder: |
        Ex. index.html, styles.css etc.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, logs, screenshots, or related links.
      placeholder: |
        Ex. Browser console shows no errors. Screenshot: (Link to Screenshot)
