name: Build JSDoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./scripts      # path to your code
        output_dir: ./scripts/docs  # output directory
