name: Build JSDoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Install dependencies
    - run: npm install 

    - name: JSdocs
    - run: npm run docs
    
